SP-4021 use spctl as dependency
Super-Protocol/solutions pull request #44
Opened 2024-04-11 18:16 UTC by Idris0v

2024-04-11 18:20 UTC, Idris0v commented on Provider Provisioner/tsconfig.build.json
> +        "noImplicitAny": false
Setting noImplicitAny to false helped eliminate errors caused by missing @types/lib libraries.

2024-04-11 18:21 UTC, Idris0v commented on Provider Provisioner/src/spctl/spctl.service.ts
spctl service is not spawning processes anymore

2024-04-11 18:22 UTC, Idris0v commented on Provider Provisioner/src/handle-input-offer.ts
> -  for (const orderStatus of orderStatuses) {
removed this loop

2024-04-11 18:23 UTC, Idris0v commented on Provider Provisioner/src/spctl/spctl.service.ts
> +import ConfigLoader from 'spctl/build/config';
notice here we use build folder from spctl module.

2024-04-12 08:43 UTC, marchuk-vlad requested changes
We don't need `download-spctl` scripts and its dependencies like `cli-progress` and `colors` anymore, do we?

2024-04-12 08:43 UTC, marchuk-vlad commented on Provider Provisioner/scripts/prepare-solution.sh
> +# npm ci --omit dev
Do we left dev dependencies intentionally ?

2024-04-16 08:50 UTC, DmitrySmv approved these changes

2024-04-16 10:21 UTC, marchuk-vlad approved these changes

2024-04-18 07:23 UTC, merged