fix(text-generation-webui): Remove dots in loader name
Super-Protocol/solutions pull request #62
Opened 2024-10-24 16:07 UTC by marchuk-vlad

2024-10-24 16:39 UTC, Idris0v approved these changes

2024-10-25 15:44 UTC, DmitrySmv requested changes

2024-10-25 15:44 UTC, DmitrySmv commented on Text Generation WebUI/src/configuration-parser.ts
> +      `${modelLoader.toLowerCase().replaceAll('.', '')}_options` as keyof typeof modelLoaderSettings
Do this change in `@super-protocol/solution-utils` please - https://github.com/Super-Protocol/solution-utils/blob/main/src/solution-configuration/get-cli-params.ts#L118

2024-10-29 09:03 UTC, DmitrySmv approved these changes

2024-10-29 09:03 UTC, merged

2024-10-29 09:53 UTC, Idris0v approved these changes